#!/bin/bash

set -eu
set -o pipefail

PRJ_NAME=artizanya-land

PRJ_PATH="`dirname \"$0\"`"
PRJ_PATH="`( cd -P \"$PRJ_PATH/..\" && pwd )`"

cd $PRJ_PATH

if [[ ! -d dist/$PRJ_NAME ]]; then
  mkdir -vp "dist/$PRJ_NAME";
fi

echo ".project/make: Copying frame to dist"

(cd frame
 if [[ ! -d node_modules ]]; then npm i; fi
 cp -vur --parents -t "../dist/$PRJ_NAME/" *)

echo ".project/make: Transpiling TypeScript files"

npx --no-install \
    tsc --listEmittedFiles

echo ".project/make: Copying build to dist"

(cd build
 find * -name "*.js" -exec cp -vu --parents -t \
      "../dist/$PRJ_NAME/" "{}" +)

echo ".project/make: Copying graphql files to dist"

(cd src
 find * -name "*.graphql" -exec cp -vu --parents -t \
      "../dist/$PRJ_NAME/" "{}" +)

echo ".project/make: Creating zip ArangoDB service"

(cd dist
 rm -vf $PRJ_NAME.zip
 zip -r "$PRJ_NAME" "$PRJ_NAME"
 echo "'dist/$PRJ_NAME.zip' created.")
