#!/bin/bash

set -eu
set -o pipefail

PRJ_NAME=artizanya-land

PRJ_PATH="`dirname \"$0\"`"
PRJ_PATH="`( cd -P \"$PRJ_PATH/..\" && pwd )`"

cd $PRJ_PATH

if [[ ! -d dist/$PRJ_NAME ]]; then
  mkdir -vp "dist/$PRJ_NAME";
fi

(cd frame
 echo "cd: '`pwd`'"
 cp -vr --parents -t "../dist/$PRJ_NAME/" *)

echo

npx --no-install \
    tsc --listEmittedFiles

echo

(cd build
 echo "cd: '`pwd`'"
 find * -name "*.js" -exec cp -v --parents -t "../dist/$PRJ_NAME/" "{}" +)

echo

(cd src
 echo "cd: '`pwd`'"
 find * -name "*.graphql" -exec cp -v --parents -t "../dist/$PRJ_NAME/" "{}" +)

echo

(cd dist/$PRJ_NAME
 echo "cd: '`pwd`'"
 npm i)

echo

(cd dist
 echo "cd: '`pwd`'"
 zip -r "$PRJ_NAME" "$PRJ_NAME"
 echo "'dist/$PRJ_NAME.zip' created.")
