#!/bin/bash

set -eu
set -o pipefail

SPATH="$(dirname "${BASH_SOURCE[0]}")"
if [ ! -d "$SPATH" ]; then SPATH="$PWD"; fi
SPATH="$(cd "$SPATH" && pwd)"

PRJ_ROOT_PATH="$SPATH/.."
PRJ_ROOT_PATH="$(cd "$PRJ_ROOT_PATH" && pwd)"

PRJ_NAME=artizanya-land

cd "$PRJ_ROOT_PATH" && echo cd $PWD

if [[ ! -d dist/$PRJ_NAME ]]; then
  mkdir -vp "dist/$PRJ_NAME";
fi

echo ".project/make: Copying frame to dist"

(cd frame
 if [[ ! -d node_modules ]]; then npm ci; fi
 cp -vur --parents -t "../dist/$PRJ_NAME/" *)

echo ".project/make: Transpiling TypeScript files"

npx --no-install \
    tsc --listEmittedFiles

echo ".project/make: Copying build to dist"

(cd build
 find * -name "*.js" -exec cp -vu --parents -t \
      "../dist/$PRJ_NAME/" "{}" +)

echo ".project/make: Copying graphql files to dist"

(cd src
 find * -name "*.graphql" -exec cp -vu --parents -t \
      "../dist/$PRJ_NAME/" "{}" +)

echo ".project/make: Creating zip ArangoDB service"

(cd dist
 rm -vf $PRJ_NAME.zip
 zip -r "$PRJ_NAME" "$PRJ_NAME"
 echo "'dist/$PRJ_NAME.zip' created.")
